### ISSUE TITLE
Make deploy:restart hook optional

### ISSUE THREAD

**Issue by hron84** [naps62/capistrano3-monit#1]
We love to use monit and this gem to manage our application lifecycle, but we moved to unicorn and it's signal-based restart mechanism rigt now, so we do not use monit:restart task anymore at deploy:restart stage. However, capistrano3-monit does not allow us to deactivate its deploy:restart hook and our application keeps restarting via monit even if signal-based restart sould be happen.

Even if we made a workaround about this (`Rake::Task['deploy:restart'].clear_actions`) we would really appreciate a way to disable this hook.

**Comment by naps62** [comment]
I'm not sure I understood your request. You want a way to opt-out of [this line](https://github.com/naps62/capistrano3-monit/blob/master/lib/capistrano/tasks/monit.rake#L44)?

If so, that can be done, although if you're up for it, I'd appreciate a Pull Request.
If not, I'll try to look into this during the next week or so

And thanks for your feedback. I'm glad this is being useful to someone else other than me :smile:

**Comment by hron84** [comment]
Yep, I mean exactly that. 

I can't contribute since I have absolute no experience working with Capistrano's / Rake's internal stuffs, and also I have no idea what do you want to do in this case since there's many options to make it opt-out (or opt-in) starting with an environment variable (which is easy to code but hard to use) to making a separated file that only loads this behavior (easy to use, easy to code, but I'm not sure how pretty solution is that). 

(also I know at least one company that uses your gem internally for all of their product since my company provides a support for their servers and we love to use monit to ensure production applications are always up).

**Comment by naps62** [comment]
@hron84 I removed the automatic hooks. The change is now available in version 0.4.0 ([this commit](https://github.com/naps62/capistrano3-monit/commit/150c3a67895eff15773e401125333d88a0baac96))

Please give it a shot, and let me know if it's working, as I'm currently unable to test this myself

**Comment by hron84** [comment]
I will give a try for it as soon as we finish this development process and I'm be able to update our deployment infrastructure.
